# Generated by Django 4.2.3 on 2023-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('photo_1', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('photo_2', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('video', models.FileField(blank=True, default='default.mp4', null=True, upload_to='')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
